#dataextract-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: dataextract-api-service
spec:
  selector:
    app: dataextract-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer
